services:    
  db:
    build:
      context: ./db
    ports:
      - "5432:5432"    
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: 1q2w3e
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 1s
      timeout: 5s
      retries: 10
    volumes:
      - pgdata:/var/lib/postgresql/data
    post_start:
      - command: ["sh", "-c", "/script.sh"]
volumes:
  pgdata: {}
